### ISSUE TITLE
Add sample for dynamic amount of task. 

### ISSUE THREAD

**Issue by Kvaz1r** [vardius/worker-pool#5]
It would be good (for copy-paste reason ;)) to have an example where amount of tasks is known at runtime and not compile time.

**Comment by vardius** [comment]
Please have a look at provided examples, whether the value comes from other function or is static doesn't rly matter. You can create worker pool dynamically during runtime same way its shown in this examples.

https://pkg.go.dev/github.com/vardius/worker-pool?tab=doc#pkg-examples

**Comment by Kvaz1r** [comment]
Yes, it seems I overlooking it or forgot what I meant ;-)
